### ISSUE TITLE
Chicken is vegetarian?

### ISSUE THREAD

**Issue by marknosal** [learn-co-curriculum/react-hooks-practice-pizza#1]
### Canvas Link

https://learning.flatironschool.com/courses/6191/assignments/228607?module_item_id=534094

### Concern

I just cloned the lab and I noticed the db.json file had the chickens vegetarian key set to true.  It doesn't affect the lab any, but I thought I would let you know!

**Comment by Matt-Eva** [comment]
Hello, and thank you for spotting this issue and providing feedback!

We have updated the GitHub repo and believe your issue to have been resolved.

We appreciate your support! 💙
